variables:
  PYHTON_MODULE: 'dockerdb'
  PYTHON_MODULE_EXTRAS: 'mongo'


.test_template: &test_def
  script:
  - pip install pytest pytest-cov pep8
  - pip install -e .[${PYTHON_MODULE_EXTRAS}]
  - docker ps -a
  - py.test --cov ${PYHTON_MODULE} --cov doc --cov test


cache:
  untracked: false
  key: pip-cache
  paths:
    - ~/.cache/pip


python2.7:
  <<: *test_def
  image: python:2.7


python3.6:
  <<: *test_def
  image: ludwigf/cde-dev-py3:713cf837766542095acaed5cf617305f24781ed1


pep8:
  image: python:3.6
  script:
    - pip install pycodestyle
    - pip install -e .[${PYTHON_MODULE_EXTRAS}]
    - pycodestyle ${PYHTON_MODULE}
