variables:
  PYHTON_MODULE: 'dockerdb'


.test_template: &test_def
  script:
  - pip install pytest pytest-cov pep8
  - pip install -e .
  - docker ps -a
  - py.test --cov ${PYHTON_MODULE} --cov doc --cov test


cache:
  untracked: false
  key: pip-cache
  paths:
    - ~/.cache/pip


python2.7:
  <<: *test_def
  image: python:2.7


python3.5:
  <<: *test_def
  image: python:3.5


python3.6:
  <<: *test_def
  image: python:3.6


pep8:
  image: python:3.6
  script:
    - pip install pycodestyle
    - pip install -e .
    - pycodestyle ${PYHTON_MODULE}
